# Generated by Django 2.1.5 on 2019-05-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190427_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagePath',
            field=models.CharField(default='pictures/emptyProduct.png', max_length=200),
        ),
    ]
